server.port=8080
server.servlet.context-path=/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testmailkafka999@gmail.com
spring.mail.password=null
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=1000

app.kafka.group-id=notification-service-group
app.kafka.topics.user-created=user-created-topic
app.kafka.topics.user-deleted=user-deleted-topic

logging.level.ru.aston.homework.intensive.notificationservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

spring.application.name=notification-service
management.endpoints.web.exposure.include=health,info
