server:
  port: 8082

spring:
  application:
    name: circuit-breaker

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

circuitbreaker:
  configs:
    default:
      sliding-window-size: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always