server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    properties:
      spring.json.trusted.packages: "ru.aston.homework.intensive.userservice.controller.dto"

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

app:
  kafka:
    topics:
      user-created: user-created-topic
      user-deleted: user-deleted-topic

circuitbreaker:
  configs:
    default:
      sliding-window-size: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always